### ISSUE TITLE
[question] How to use it ? 

### ISSUE THREAD

**Issue by Tinostarn** [dagstuan/ng2-redux-router#9]
Hello,

Sorry if my question seems stupid, but despite the readme which explains well how to setup and configure ng2-redux-router in a ng2 app, I simply can't figure out how to use it !
What I want to do is to make a redirection after a http post in an action creator service. I thought I could find an practical case in the example folder, but there's nothing. 

Thx for guiding me

**Comment by born2net** [comment]
Well my question is even more stupid... "why would you use it"?
No seriously, I am trying to understand this lib and why it exists.

So this lib will allow you to listen to route changes from the store?
I am not sure why would one need this pattern? Am I missing something?
You can just DI and listen to routes via observales inside ng2

regards,

Sean.

**Comment by dagstuan** [comment]
@born2net if you don't see a use case for it, don't use it :) Its not needed in any way for redux to function. However, some apps may need to have the current router location in the state so actions can have different results depending on where the user is. The reason I made this is because I don't like to spread the state into different containers (both redux and router), and prefer to keep the state in one place, in this case, the redux store. As a sidenote, this also enables functionality such as time travel to work with the router as well, since the router location always stays in sync with the store location, this can in some cases make debugging easier. Did this answer your question?

@supertino7 the `README.md` specifies how to set it up. Can you be more specific as to what you are struggling with? The library doesnt really require a lot of "use", since its main job is to sync the state in redux with the router-state. If you want to do a redirection after an HTTP POST you should inject the router in the action creator service and use the router to redirect.

**Comment by born2net** [comment]
@dagstuan I fully understand (didn't mean to sound condescending) and this is a great explanation.
I actually recommend you add that do the front page readme.md
tx again,
Sean.
